add review note
DBCDK/bibdk pull request #110
Opened 2020-12-29 15:25 UTC by rikke-dbc

2021-01-04 05:45 UTC, dbclkh requested changes
Sørg som minimum for dokumentation og return value for getRelations metoden.

2021-01-04 05:45 UTC, dbclkh commented on modules/bibdk_reviews/bibdk_reviews.material_review.inc
> +  $type = $review_ids['type'];
Er du sikker på at type altid er sat?

2021-01-04 05:45 UTC, dbclkh commented on modules/bibdk_reviews/bibdk_reviews.material_review.inc
> +  return $render_array;
Spar denne line væk og bare skriv return array(... i line 102.

2021-01-04 05:45 UTC, dbclkh commented on modules/bibdk_reviews/includes/BibdkReview.inc
> +  function getRelations() {
Dokumentation og return variable mangler.

2021-01-04 08:12 UTC, rikke-dbc commented on modules/bibdk_reviews/bibdk_reviews.material_review.inc
> +  $type = $review_ids['type'];
tja, jeg sætter den selv, men jeg laver et check :)

2021-01-05 07:58 UTC, dbclkh approved these changes
Fino herfra.

2021-01-05 07:59 UTC, merged